spring:
  profiles.active: development
  security:
    basic:
      enabled: false
hatenote:
  notesPerPage: 5
management:
    context-path: /audit
---
spring:
  profiles: development
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: hatedb
---
spring:
  profiles: production
  data:
    mongodb:
      host: XXX.XXX.XXX.XXX
      port: 27017
      database: hatedb